#!/bin/bash

function send_notification() {
    echo "$1"
}

function assert_success() {
    "${@}"
    local status=${?}
    if [ ${status} -ne 0 ]; then
        send_notification "### Error ${status} at: ${BASH_LINENO[*]} ###"
        exit ${status}
    fi
}

app=planner-text-help
version=0.1

assert_success ./gradlew build
assert_success docker build -t $app:"$version" .
assert_success docker tag $app:"$version" $app
assert_success docker push $app
